---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: train-schedule-deployment
 spec:
   replicas: 2
   selector:
    matchLabels:
      app: train-schedule
   template:
     metadata:
       labels:
         app: train-schedule
     spec:
       containers:
         - name: train-schedule
           image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
           ports:
            - containerPort: 8080
            
---
 apiVersion: v1
 kind: Service
 metadata:
   name: train-schedule-service
 spec:
   selector:
     app: train-schedule
   ports:
    - protocol: TCP
      port: 8080
      nodePort: 8080
